name: Keep Service Warm
on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Service
        run: |
          curl -X GET "https://transcripts-search.onrender.com/cron"
          curl -X GET "https://transcripts-search.onrender.com/ping"
